CREATE TABLE users(
id SERIAL PRIMARY KEY,
username TEXT NOT NULL
);

CREATE TABLE chats(
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE messages(
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE,
chat_id INTEGER REFERENCES chats(id)
);